### PR TITLE
Citations fix AND JSON error fix for newer postgres

### PR DESCRIPTION
**Pull request by jaseiler**
the citations code was easy.  the JSON fix took all day!

### CODE REVIEW

**Comment by codersquid** [comment]
Thanks!

When would you like to deploy? Let's have a checklist for deploying, here is one off the top of my head, and we should refine it once we are ready to go so that we list out commands.

for staging
- [ ] sudo supervisorctl stop researchcompendia
- [ ] get prod database dump
- [ ] dropdb in staging and replace it with the the prod db
- [ ] sudo supervisorctl start researchcompendia
- [ ] make sure things are copacetic with the version of the site in staging
- [ ] sudo supervisorctl stop researchcompendia
- [ ] run the sql to change all the django json fields that are blank to {} (don't alter the columns to the json type since postgres 9.1 doesn't have a json type)
- [ ] make new release (this is some steps with git, and I use git flow to do releases)
- [ ] deploy the new release
- [ ] sudo supervisorctl start researchcompendia
- [ ] make sure things are copacetic again.

once everything runs smoothly, then we do all that in prod but with a few extra steps, like disable the researchcompendia site and enable the maintenance site and restart nginx.

(I miss heroku, we didn't have to go through as many steps. there were other annoyances with heroku though)

**Comment by jaseiler** [comment]
I messed up the __0008_auto__add_field_…py by deleting a paren. I fixed it, I'll make a new pull request soon.  
I'm not sure about the "dropdb in staging and replace it with the the prod db" step.
My version should be back compatible, for older postgres.
But for newer postgresql, the problem will be that all json database entries will need to have "" replaced with "{}" for: related_urls, authorship, and bibjson (and any other json entries).
Once that is true for any dbs it should work for all postgres versions (I think).

**Comment by codersquid** [comment]
You maybe could do

git fetch

git rebase -i origin/master

and then in the editor that comes up change pick to s or f depending on whether you want to squash or do a fixup for the merges, and then you could push to your branch again and this pull request can still be used.

I admit I am very fuzzy on this.

**Comment by codersquid** [comment]
actually, I think it is okay not to squash the commits, we could just merge this right? It will take both commits. I think things will be okay.

**Pull request closed without merging**
